### ISSUE TITLE
Error handling response: TypeError: Cannot read properties of null (reading 'appendChild')   at <URL>

### ISSUE THREAD

**Issue by xhwsd** [zuisong/docsify-kroki#3]
Error handling response: TypeError: Cannot read properties of null (reading 'appendChild') at <URL>

**Comment by zuisong** [comment]
could you make demo repo to reproduce this error ?

And can you tell me  your browser version?

**Comment by xhwsd** [comment]
view demo , browser Microsoft Edge v103.0.1264.49 64-bit

**Comment by zuisong** [comment]
Could you try that browse the demo page in private mode without any browser extensions?

**Comment by xhwsd** [comment]
呵呵，还没睡？

**Comment by xhwsd** [comment]
测试发现，的确在没浏览器插件下不报错了~

**Comment by zuisong** [comment]
Maybe you have installed some plugins to render plantuml, this error is produced by those plugins.

可能是你安装了一些渲染 plantuml 的插件，这个错是这些插件产生的。
