### ISSUE TITLE
Load diagrams from external files

### ISSUE THREAD

**Issue by cippaciong** [zuisong/docsify-kroki#4]
Hello, thank you for your work on this plugin.

I was wondering if it would be possible to load a diagram from an external file instead of embedding it directly in the markdown file.
Some diagram languages are short and human readable and fits well to be written inline. Others, like `excalidraw` for example, are quite long and they would make the documentation hard to edit.

It would be nice if instead of doing this
```markdown
Foo
\```excalidraw
[Very long diagram code]
\```
Bar
```

We could do something like this:
```markdown
Foo
![excalidraw](path/to/diagram.json)
Bar
```

**Comment by zuisong** [comment]
thanks, next version will support this feature.

**Comment by zuisong** [comment]
1.0.19 released. 
now you can load diagrams from external files as it.
```markdown

![kroki-excalidraw](link/to/diagram.json)

![kroki-plantuml](link/to/plantuml.txt)
```

https://zuisong.github.io/docsify-kroki/#/?id=excalidraw-from-external-files

**Comment by cippaciong** [comment]
Amazing! Thank you so much 
I'll give it a try in the next few days 🙂
