### ISSUE TITLE
414 Request URI Too Long

### ISSUE THREAD

**Issue by cippaciong** [zuisong/docsify-kroki#5]
Hi, I was trying to load an excalidraw diagram (tried using both embedded and external files), but I get this error from kroki because the URI is too long:

```
Error 414: The request URI's length exceeds 4096. You can update this value by setting KROKI_MAX_URI_LENGTH environment variable. Please read: https://docs.kroki.io/kroki/setup/configuration/#_max_uri_length for more information.
```

According to https://github.com/yuzutech/kroki-go/issues/11, a possible solution would be to use `POST` requests for longer payloads.

To give you a reference, your excalidraw test is `16KB/695 lines` long and it works fine, while mine is `33KB/1483 lines`.

**Comment by zuisong** [comment]
we can't use post request because of CORS.

kroki.io doesn't support CORS request

```
Access to fetch at 'http://kroki.io/plantuml/svg/' from origin 'http://127.0.0.1:8080' has been blocked by CORS policy: 
No 'Access-Control-Allow-Origin' header is present on the requested resource.
 If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```


about CORS , you can read this article
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by cippaciong** [comment]
Hi @zuisong, sorry in advance if my reply doesn't make a lot of sense, I'm not an expert in Javascript or CORS.

I tried to reproduce the error using a plain html+js file while serving it on localhost using a python server, but I was able to get the svg from kroki.

![image](https://user-images.githubusercontent.com/2799612/207026424-9195a09a-8197-4d87-930f-5778093834b9.png)

This is the code I used:
```html
<!-- kroki.html -->
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>title</title>
    <link rel="stylesheet" href="style.css">
  </head>
  <body>
    <svg></svg>
    <script>

      diagram = `
      [Person]
      *name
      height
      weight
      +birth_location_id

      [Location]
      *id
      city
      state
      country

      Person *--1 Location
      `
      fetch('https://kroki.io/erd/svg', {
        method: 'POST',
        body: diagram,
        headers: {
          'Content-Type': 'text/plain'}
        })
        .then(res => res.text())
        .then(svg => document.body.insertAdjacentHTML("afterbegin", svg));
    </script>
  </body>
</html>
```

```python
# run with: python3 server.py
import http.server
import socketserver

class MyHttpRequestHandler(http.server.SimpleHTTPRequestHandler):
    def do_GET(self):
        if self.path == '/':
            self.path = 'kroki.html'
        return http.server.SimpleHTTPRequestHandler.do_GET(self)

# Create an object of the above class
handler_object = MyHttpRequestHandler

PORT = 8000
my_server = socketserver.TCPServer(("", PORT), handler_object)

# Star the server
my_server.serve_forever()
```

Does this setup make any sense at all? I wonder why it's working in this case.
Thanks 🙂

**Comment by zuisong** [comment]
the kroki server can only support cross domain using the https protocol. I use the http protocol, so cross domain is not supported

then. next version will support use use POST requests for longer payloads.

**Comment by zuisong** [comment]
1.0.20 released,  now this plugin support use use POST requests for longer payloads.

website must hold on https protocol
