### ISSUE TITLE
Allow to resize rendered diagrams

### ISSUE THREAD

**Issue by cippaciong** [zuisong/docsify-kroki#6]
Hi, I'm once again here to request an additional feature.
Would it be possible to allow diagrams resizing similarly to what we can do with normal images ([docs](https://docsify.js.org/#/helpers?id=resizing))?

It would be great if we could have something like this:
```md
![kroki-excalidraw](path/to/diagram.json ':size=60%')
```

Thanks :)

**Comment by zuisong** [comment]
We are not rendered into `img` tag, so change size cannot be implemented.

**Comment by zuisong** [comment]
We have two way to write diagrams, `embed code` and `load from external files` . They cannot have the same configuration method.
